In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good deveoper',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good deveoper',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[5679, 4504, 761, 3785],
 [5679, 4504, 761, 3902],
 [5679, 3996, 761, 9191],
 [3083, 4268, 4687, 9423, 9823],
 [3083, 4268, 4687, 9423, 1926],
 [4201, 5679, 8381, 761, 3096],
 [694, 280, 654, 9423]]

In [9]:
[one_hot(words,10) for words in sent]

[[9, 4, 5, 5],
 [9, 4, 5, 5],
 [9, 9, 5, 2],
 [5, 2, 7, 9, 4],
 [5, 2, 7, 9, 9],
 [7, 9, 2, 5, 9],
 [1, 1, 6, 9]]

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5679 4504  761 3785]
 [   0    0    0    0 5679 4504  761 3902]
 [   0    0    0    0 5679 3996  761 9191]
 [   0    0    0 3083 4268 4687 9423 9823]
 [   0    0    0 3083 4268 4687 9423 1926]
 [   0    0    0 4201 5679 8381  761 3096]
 [   0    0    0    0  694  280  654 9423]]


In [14]:
dim = 10

In [17]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\vinay\OneDrive\Desktop\Udemy KrisNaik GenAI\ANN_new\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[[ 0.02769974, -0.04015458,  0.0251968 , -0.02196779,
          0.02043326, -0.01656143, -0.03147107,  0.00205325,
         -0.01583146, -0.01584852],
        [ 0.02769974, -0.04015458,  0.0251968 , -0.02196779,
          0.02043326, -0.01656143, -0.03147107,  0.00205325,
         -0.01583146, -0.01584852],
        [ 0.02769974, -0.04015458,  0.0251968 , -0.02196779,
          0.02043326, -0.01656143, -0.03147107,  0.00205325,
         -0.01583146, -0.01584852],
        [ 0.02769974, -0.04015458,  0.0251968 , -0.02196779,
          0.02043326, -0.01656143, -0.03147107,  0.00205325,
         -0.01583146, -0.01584852],
        [-0.04520993, -0.00156987,  0.02639784,  0.02307649,
          0.03289193, -0.01009367,  0.01391161, -0.02287688,
          0.04918433,  0.0410241 ],
        [-0.02588893, -0.02475229, -0.00445145,  0.01136197,
          0.04776904,  0.03039969,  0.03942864,  0.02290524,
         -0.01597459,  0.0065536 ],
        [ 0.03957209,  0.04003615, -0.01318901, -0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 5679, 4504,  761, 3785], dtype=int32)